server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlexZheng1225/aispringcould.git
          search-paths: config
          username: your account name
          passphrase: your account password
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
